[package]
name = "speck_logger_coloring"
version = "0.1.0"
edition = "2024"

[dependencies]
speck_logger = { path = "../speck_logger" }
speck_text_coloring = { path = "../speck_text_coloring" }
chrono = "0.4.40"